services:
  amqtt:
    image: amqtt
    environment:
      - NEWRELIC_CONFIG_INI=/app/conf/newrelic.ini
    container_name: amqtt
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8883:8883"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./newrelic.ini:/app/conf/newrelic.ini
      - /etc/letsencrypt:/app/cert:ro
