"""MQTT Constants for the AMQTT library."""

# MQTT versions
MQTT_3_1 = 0x03
MQTT_3_1_1 = 0x04
MQTT_5_0 = 0x05

# Message types
CONNECT = 0x01
CONNACK = 0x02
PUBLISH = 0x03
PUBACK = 0x04
PUBREC = 0x05
PUBREL = 0x06
PUBCOMP = 0x07
SUBSCRIBE = 0x08
SUBACK = 0x09
UNSUBSCRIBE = 0x0A
UNSUBACK = 0x0B
PINGREQ = 0x0C
PINGRESP = 0x0D
DISCONNECT = 0x0E
AUTH = 0x0F  # MQTT5 AUTH packet

# QoS levels
QOS_0 = 0x00
QOS_1 = 0x01
QOS_2 = 0x02

# MQTT5 reason codes
# Connection reason codes
SUCCESS = 0x00
NORMAL_DISCONNECTION = 0x00
GRANTED_QOS_0 = 0x00
GRANTED_QOS_1 = 0x01
GRANTED_QOS_2 = 0x02
DISCONNECT_WITH_WILL_MESSAGE = 0x04
NO_MATCHING_SUBSCRIBERS = 0x10
NO_SUBSCRIPTION_EXISTED = 0x11
CONTINUE_AUTHENTICATION = 0x18
RE_AUTHENTICATE = 0x19
UNSPECIFIED_ERROR = 0x80
MALFORMED_PACKET = 0x81
PROTOCOL_ERROR = 0x82
IMPLEMENTATION_SPECIFIC_ERROR = 0x83
UNSUPPORTED_PROTOCOL_VERSION = 0x84
CLIENT_IDENTIFIER_NOT_VALID = 0x85
BAD_USERNAME_OR_PASSWORD = 0x86
NOT_AUTHORIZED = 0x87
SERVER_UNAVAILABLE = 0x88
SERVER_BUSY = 0x89
BANNED = 0x8A
SERVER_SHUTTING_DOWN = 0x8B
BAD_AUTHENTICATION_METHOD = 0x8C
KEEP_ALIVE_TIMEOUT = 0x8D
SESSION_TAKEN_OVER = 0x8E
TOPIC_FILTER_INVALID = 0x8F
TOPIC_NAME_INVALID = 0x90
PACKET_IDENTIFIER_IN_USE = 0x91
PACKET_IDENTIFIER_NOT_FOUND = 0x92
RECEIVE_MAXIMUM_EXCEEDED = 0x93
TOPIC_ALIAS_INVALID = 0x94
PACKET_TOO_LARGE = 0x95
MESSAGE_RATE_TOO_HIGH = 0x96
QUOTA_EXCEEDED = 0x97
ADMINISTRATIVE_ACTION = 0x98
PAYLOAD_FORMAT_INVALID = 0x99
RETAIN_NOT_SUPPORTED = 0x9A
QOS_NOT_SUPPORTED = 0x9B
USE_ANOTHER_SERVER = 0x9C
SERVER_MOVED = 0x9D
SHARED_SUBSCRIPTIONS_NOT_SUPPORTED = 0x9E
CONNECTION_RATE_EXCEEDED = 0x9F
MAXIMUM_CONNECT_TIME = 0xA0
SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED = 0xA1
WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED = 0xA2

# MQTT5 property identifiers
PAYLOAD_FORMAT_INDICATOR = 0x01
MESSAGE_EXPIRY_INTERVAL = 0x02
CONTENT_TYPE = 0x03
RESPONSE_TOPIC = 0x08
CORRELATION_DATA = 0x09
SUBSCRIPTION_IDENTIFIER = 0x0B
SESSION_EXPIRY_INTERVAL = 0x11
ASSIGNED_CLIENT_IDENTIFIER = 0x12
SERVER_KEEP_ALIVE = 0x13
AUTHENTICATION_METHOD = 0x15
AUTHENTICATION_DATA = 0x16
REQUEST_PROBLEM_INFORMATION = 0x17
WILL_DELAY_INTERVAL = 0x18
REQUEST_RESPONSE_INFORMATION = 0x19
RESPONSE_INFORMATION = 0x1A
SERVER_REFERENCE = 0x1C
REASON_STRING = 0x1F
RECEIVE_MAXIMUM = 0x21
TOPIC_ALIAS_MAXIMUM = 0x22
TOPIC_ALIAS = 0x23
MAXIMUM_QOS = 0x24
RETAIN_AVAILABLE = 0x25
USER_PROPERTY = 0x26
MAXIMUM_PACKET_SIZE = 0x27
WILDCARD_SUBSCRIPTION_AVAILABLE = 0x28
SUBSCRIPTION_IDENTIFIER_AVAILABLE = 0x29
SHARED_SUBSCRIPTION_AVAILABLE = 0x2A

# MQTT5 property types
PROPERTY_TYPE_BYTE = 0x01
PROPERTY_TYPE_TWO_BYTE_INTEGER = 0x02
PROPERTY_TYPE_FOUR_BYTE_INTEGER = 0x03
PROPERTY_TYPE_VARIABLE_BYTE_INTEGER = 0x04
PROPERTY_TYPE_BINARY_DATA = 0x05
PROPERTY_TYPE_UTF8_ENCODED_STRING = 0x06
PROPERTY_TYPE_UTF8_STRING_PAIR = 0x07

# MQTT5 property types mapping
PROPERTY_TYPES = {
    PAYLOAD_FORMAT_INDICATOR: PROPERTY_TYPE_BYTE,
    MESSAGE_EXPIRY_INTERVAL: PROPERTY_TYPE_FOUR_BYTE_INTEGER,
    CONTENT_TYPE: PROPERTY_TYPE_UTF8_ENCODED_STRING,
    RESPONSE_TOPIC: PROPERTY_TYPE_UTF8_ENCODED_STRING,
    CORRELATION_DATA: PROPERTY_TYPE_BINARY_DATA,
    SUBSCRIPTION_IDENTIFIER: PROPERTY_TYPE_VARIABLE_BYTE_INTEGER,
    SESSION_EXPIRY_INTERVAL: PROPERTY_TYPE_FOUR_BYTE_INTEGER,
    ASSIGNED_CLIENT_IDENTIFIER: PROPERTY_TYPE_UTF8_ENCODED_STRING,
    SERVER_KEEP_ALIVE: PROPERTY_TYPE_TWO_BYTE_INTEGER,
    AUTHENTICATION_METHOD: PROPERTY_TYPE_UTF8_ENCODED_STRING,
    AUTHENTICATION_DATA: PROPERTY_TYPE_BINARY_DATA,
    REQUEST_PROBLEM_INFORMATION: PROPERTY_TYPE_BYTE,
    WILL_DELAY_INTERVAL: PROPERTY_TYPE_FOUR_BYTE_INTEGER,
    REQUEST_RESPONSE_INFORMATION: PROPERTY_TYPE_BYTE,
    RESPONSE_INFORMATION: PROPERTY_TYPE_UTF8_ENCODED_STRING,
    SERVER_REFERENCE: PROPERTY_TYPE_UTF8_ENCODED_STRING,
    REASON_STRING: PROPERTY_TYPE_UTF8_ENCODED_STRING,
    RECEIVE_MAXIMUM: PROPERTY_TYPE_TWO_BYTE_INTEGER,
    TOPIC_ALIAS_MAXIMUM: PROPERTY_TYPE_TWO_BYTE_INTEGER,
    TOPIC_ALIAS: PROPERTY_TYPE_TWO_BYTE_INTEGER,
    MAXIMUM_QOS: PROPERTY_TYPE_BYTE,
    RETAIN_AVAILABLE: PROPERTY_TYPE_BYTE,
    USER_PROPERTY: PROPERTY_TYPE_UTF8_STRING_PAIR,
    MAXIMUM_PACKET_SIZE: PROPERTY_TYPE_FOUR_BYTE_INTEGER,
    WILDCARD_SUBSCRIPTION_AVAILABLE: PROPERTY_TYPE_BYTE,
    SUBSCRIPTION_IDENTIFIER_AVAILABLE: PROPERTY_TYPE_BYTE,
    SHARED_SUBSCRIPTION_AVAILABLE: PROPERTY_TYPE_BYTE,
}
